Repository UBC-MDS/DSCI-532_2024_7_ds-compensation, pull requests merged in 2024-04, with the labels that each got.

#30 Requirement file renamed
  requirements.txt
Labels: bug

#34 Added the demo GIF file under img folder
  img/demo.gif
Labels: documentation

#51 Added the box plot by work arrangement
  src/callbacks.py
Labels: enhancement

#56 Added the wrangling.py script containing the data warngling function.
  src/callbacks.py
  src/data_wrangling.py
Labels: enhancement

#88 Caching Added
  data/raw/ds_salaries.parquet
  environment.yaml
  src/callbacks.py
  src/data.py
Labels: enhancement

#91 Updated the gif file
  img/demo.gif
Labels: documentation, enhancement
